# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FMlVs_TN11RY2kUlTEQ1U8K9Nh1pq6bS
"""

import numpy as np
import matplotlib.pyplot as plt
A = 1
B = 1
C = 0
D = 0
x = np.linspace(-2 * np.pi, 2 * np.pi, 1000)
y = A * np.sin(B * (x - C)) + D
plt.plot(x, y)
plt.title('Sinusoida grafigi')
plt.xlabel('x')
plt.ylabel('y')
plt.grid()
plt.axhline(0, color='black',linewidth=0.5, ls='--')
plt.axvline(0, color='black',linewidth=0.5, ls='--')
plt.show()